# Generated by Django 3.2.7 on 2021-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210917_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='After10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
