# Generated by Django 3.2.7 on 2021-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_after10'),
    ]

    operations = [
        migrations.CreateModel(
            name='After12Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='After12Commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='After12Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
