# Generated by Django 3.2.8 on 2021-10-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_after12arts_after12commerce_after12science'),
    ]

    operations = [
        migrations.CreateModel(
            name='After10colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='After12colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
