# Generated by Django 3.2.8 on 2021-10-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_after10colleges_after12colleges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='after10colleges',
            old_name='question',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='after12colleges',
            old_name='question',
            new_name='college',
        ),
    ]
