# Generated by Django 3.2.8 on 2021-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211014_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='after10colleges',
            name='college',
        ),
        migrations.RemoveField(
            model_name='after12colleges',
            name='college',
        ),
        migrations.AddField(
            model_name='after10colleges',
            name='college_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='after10colleges',
            name='college_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='after10colleges',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='after12colleges',
            name='college_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='after12colleges',
            name='college_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='after12colleges',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
