# Generated by Django 3.2.8 on 2021-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211014_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after10colleges',
            name='college_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='after10colleges',
            name='college_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
