# Generated by Django 3.2.8 on 2021-10-14 13:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211014_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='after10colleges',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='after12colleges',
            name='phone',
        ),
        migrations.AddField(
            model_name='after10colleges',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='after12colleges',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
