# Generated by Django 3.2.8 on 2021-10-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211014_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='After12colleges',
            new_name='After12engcolleges',
        ),
    ]
