# Generated by Django 3.2.8 on 2021-10-14 15:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_after12colleges_after12engcolleges'),
    ]

    operations = [
        migrations.CreateModel(
            name='After12medicolleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='', max_length=1000)),
                ('college_address', models.CharField(default='', max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
            ],
        ),
    ]
