# Generated by Django 3.2.8 on 2022-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('answer', models.CharField(choices=[('Dislike', 'Dislike'), ('Neutral', 'Neutral'), ('Enjoy', 'Enjoy')], max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='test_after',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
