# Generated by Django 3.2.8 on 2022-01-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_result12sci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='After10',
        ),
    ]
