# Generated by Django 3.2.8 on 2022-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_delete_after10'),
    ]

    operations = [
        migrations.CreateModel(
            name='After10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
