# Generated by Django 3.2.8 on 2022-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_after10'),
    ]

    operations = [
        migrations.AddField(
            model_name='after10',
            name='question_type',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
