# Generated by Django 3.2.8 on 2022-01-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220131_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='email',
        ),
        migrations.AddField(
            model_name='result',
            name='username',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
