# Generated by Django 3.2.7 on 2022-02-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220131_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result10Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count_science', models.CharField(max_length=10)),
                ('count_arts', models.CharField(max_length=10)),
                ('count_commerce', models.CharField(max_length=10)),
            ],
        ),
    ]
