# Generated by Django 3.2.7 on 2022-02-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_result10count'),
    ]

    operations = [
        migrations.AddField(
            model_name='after10',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
